### ISSUE TITLE
staging環境にdeploy出来るようにする

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/SyncPod-BFF#7]
## 目的はなんですか
早めにdeployしてdeploy時に発生するエラーを未然に処理しておくことと、どこからでも最新の状態が確認でできるようにする。

ドメイン：staging.bff.sync-pod.com
staging.app.sync-pod.com からのみたたけるようにする

## どのような方法が考えられますか
AWSのEC2にdeploy

**Comment by euglena1215** [comment]
bffよりもgraphqlとかgqlのほうがよさそう

**Comment by mori-atsushi** [comment]
gql.sync-pod.com なら/graphqlって入ってるのが妙な気もした
